### ISSUE TITLE
init should split "name" into fileName and extensionName

### ISSUE THREAD

**Issue by typemytype** [typemytype/extensionBundle#2]
add `fileName` argument during init --> filename with or without the extension extension
add `extensionName` argument during init --> look for extension with this name

deprecate `name` with a fallback to `fileName`

FYI @roberto-arista 

see the discord chat https://discord.com/channels/1052516637489766411/1207357255239082014

**Comment by roberto-arista** [comment]
this should be solved with the adjusted attributes we agreed upon today, right?

**Comment by typemytype** [comment]
yes, keep `name` the rest is done by the subclass inside RoboFont
